import Head from "next/head";
import NavBar from "../components/Navbar/Navbar";
import Dashboard from "../components/Dashboard";
import client from "../apollo-client";
import { USER_DATA_QUERY } from "../query.js";

export default function Home({ viewer }) {
  return (
    <div>
      <Head>
        <title>Oko.press Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500;700&family=Roboto:wght@300;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <NavBar />
      <Dashboard data={viewer} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const { data } = await client.query({
    query: USER_DATA_QUERY,
  });

  return {
    props: {
      viewer: data.viewer,
    },
  };
};
